try:
    print(a)
except NameError as result:
    print(result)
